tasks:
  - name: Prebuild tasks
    before: |
      npm install -g @angular/cli
    init: |
      cd jet-pdf
      npm install
  - name: Open preview    
    command: |
      cd jet-pdf
      ng serve

ports:
  - port: 4200
    onOpen: open-browser